name: amazon_cognito_identity_dart_2
version: 3.6.2
homepage: https://github.com/furaiev/amazon-cognito-identity-dart-2
description: Unofficial Amazon Cognito Identity Provider Dart SDK, to add user
  sign-up / sign-in to your mobile and web apps with AWS Cloud Services. Based
  on amazon-cognito-identity-dart

environment:
  sdk: '>=2.13.0 <4.0.0'

dependencies:
  convert: ^3.1.1
  crypto: ^3.0.3
  http: ^1.0.0
  js: ">=0.6.7 <0.8.0"

dev_dependencies:
  flutter_lints: ">=2.0.1 <4.0.0"
  test: ^1.24.3
